Repository betagouv/rdv-service-public, pull requests merged in 2020-06, with the labels that each got.

#692 add IE 11 to browserslist
  .browserslistrc
Labels: devops

#691 bump devise_invitable + fix a few deprecation warnings
  Gemfile.lock
  app/controllers/lieux_controller.rb
  app/views/agents/agents/show.html.slim
  app/views/agents/rdvs/_rdv.html.slim
  app/views/agents/stats/index.html.slim
  spec/features/agents/agent_can_see_users_rdv_spec.rb
  spec/features/users/user_views_his_rdvs_spec.rb
  spec/support/page_spec_helper.rb
Labels: devops

#700 Refactor/yarn upgrade
  yarn.lock
Labels: devops

#704 fix sending SMS on RDV update
  app/services/notifications/rdv/rdv_updated_service.rb
Labels: bug

#703 prevent window alerts for n+1 queries from bullet in dev
  config/environments/development.rb
Labels: devops

#702 fix inviting agent with email capitalized differently
  app/controllers/agents/invitations_controller.rb
  spec/controllers/agents/invitations_controller_spec.rb
Labels: bug

#699 Renomer le .online d'un motif
  app/controllers/agents/motifs_controller.rb
  app/controllers/lieux_controller.rb
  app/dashboards/motif_dashboard.rb
  app/helpers/motifs_helper.rb
  app/models/lieu.rb
  app/models/motif.rb
  app/models/rdv.rb
  app/models/service.rb
  app/services/creneaux_builder_service.rb
  app/views/agents/motifs/_form.html.slim
  app/views/agents/motifs/show.html.slim
  app/views/mailers/users/rdv_mailer/rdv_cancelled_by_agent.html.slim
  app/webpacker/stylesheets/components/_motifs.scss
  config/locales/models/motif.fr.yml
  config/locales/motifs.yml
  db/migrate/20200604083849_rename_motif_online.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/lieux_controller_spec.rb
  spec/controllers/welcome_controller_spec.rb
  spec/factories/motif.rb
  spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb
  spec/features/users/user_can_search_rdv_spec.rb
  spec/helpers/motifs_helper_spec.rb
  spec/helpers/rdvs_helper_spec.rb
  spec/models/creneau_spec.rb
  spec/models/lieu_spec.rb
  spec/models/service_spec.rb
  spec/services/creneaux_builder_service_spec.rb
  spec/services/find_availability_service_spec.rb
Labels: refacto

#695 [Refacto] Uniformiser les 7 layouts slim,
  app/controllers/agent_auth_controller.rb
  app/controllers/agents/rdv_wizard_steps_controller.rb
  app/controllers/agents/rdvs_controller.rb
  app/controllers/ehpads_controller.rb
  app/controllers/lieux_controller.rb
  app/controllers/static_pages_controller.rb
  app/controllers/stats_controller.rb
  app/controllers/user_auth_controller.rb
  app/controllers/users/registrations_controller.rb
  app/controllers/welcome_controller.rb
  app/views/agents/rdv_wizard_steps/step1.html.slim
  app/views/agents/rdv_wizard_steps/step2.html.slim
  app/views/agents/rdv_wizard_steps/step3.html.slim
  app/views/common/_footer.html.slim
  app/views/common/_head_agent.html.slim
  app/views/common/_head_landing.html.slim
  app/views/common/_head_users.html.slim
  app/views/layouts/_flash.html.slim
  app/views/layouts/_footer_dashboard.html.slim
  app/views/layouts/application-small.html.slim
  app/views/layouts/application.html.slim
  app/views/layouts/application_agent.html.slim
  app/views/layouts/application_user.html.slim
  app/views/layouts/landing.html.slim
  app/views/layouts/welcome.html.slim
  app/views/layouts/welcome_agent.html.slim
  app/views/static_pages/disclaimer.html.slim
  app/views/static_pages/mds.html.slim
  app/views/static_pages/terms.html.slim
  app/views/stats/index.html.slim
  app/webpacker/packs/application.js
  app/webpacker/packs/application_agent.js
  app/webpacker/packs/application_users.js
  app/webpacker/packs/landing.js
  app/webpacker/stylesheets/application.scss
  app/webpacker/stylesheets/application_agent.scss
  app/webpacker/stylesheets/application_users.scss
  app/webpacker/stylesheets/landing.scss
Labels: refacto

#713 fix export format from ods to xls + remove dead code
  app/controllers/agents/organisations/rdvs_controller.rb
  app/controllers/agents/stats_controller.rb
  app/views/agents/stats/index.html.slim
  config/initializers/mime_types.rb
Labels: bug

#722 met à jour ruby en version 2.7.1
  .circleci/config.yml
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: ruby
