Repository betagouv/rdv-service-public, pull requests merged in 2022-11, with the labels that each got.

#2973 Documentation Rswag motifs
  spec/requests/api/v1/motifs_request_spec.rb
  spec/swagger_helper.rb
  swagger/v1/api.json
Labels: Aides Jeunes

#3004 Élargie la policy sur les RDV pour afficher tous les RDV des organisations auxquelles l'agent accède
  app/controllers/api/v1/rdvs_controller.rb
  app/policies/agent/rdv_policy.rb
Labels: bug

#3020 Affiche les prochains créneaux disponibles dans les semaines qui suivent pour des motifs qui ne sont pas sur place
  app/controllers/admin/creneaux/agent_searches_controller.rb
  spec/requests/admin/creneaux/agent_searches_spec.rb
Labels: bug, .S, -92

#3021 Renomme une méthode pour la faire correspondre à l'autre méthode
  app/services/users/geo_search.rb
Labels: tech, .S

#3026 Bugfix : clé de "fragment cache" instable instable en prod
  app/helpers/i18n_cache_helper.rb
  app/views/admin/rdvs/index.html.slim
Labels: bug, tech

#3029 Use Rswag DSL for paginated requests spec
  spec/requests/api/v1/paginated_request_spec.rb
Labels: Aides Jeunes

#3024 Incite à mettre l'url de review app dans la pr
  .github/pull_request_template.md
Labels: .S, Documentation

#3032 Automatise test RGAA sur new session
  app/views/common/_franceconnect_button.html.slim
  spec/features/accessibility/users_pages_spec.rb
Labels: .S

#3046 feat(migration): Add rsa_main_tendue motif category
  app/models/concerns/motif/category.rb
  app/models/motif.rb
  config/locales/models/motif.fr.yml
  db/migrate/20221108181921_add_rsa_main_tendue_to_motif_category.rb
  db/schema.rb
  docs/domain_model.svg
Labels: data.insertion

#3028 Masque par défaut les usagers marqués supprimé
  app/controllers/admin/users_controller.rb
  app/helpers/users_helper.rb
  app/models/user.rb
  app/services/duplicate_users_finder_service.rb
  app/views/admin/merge_users/_user_relatives.html.slim
  app/views/admin/users/show.html.slim
  app/views/users/users/edit.html.slim
  spec/controllers/admin/users_controller_spec.rb
  spec/models/user_spec.rb
Labels: bug, -92

#3022 Document absence API with rswag
  app/controllers/api/v1/absences_controller.rb
  app/controllers/api/v1/users_controller.rb
  spec/requests/api/v1/absences_request_spec.rb
  spec/requests/api/v1/motifs_request_spec.rb
  spec/requests/api/v1/users_request_spec.rb
  spec/swagger_helper.rb
  swagger/v1/api.json
Labels: Aides Jeunes

#3014 Changement webhooks pour mise en place des status de participations dans RDV Insertion
  app/blueprints/motif_blueprint.rb
  app/blueprints/rdvs_users_blueprint.rb
  app/models/concerns/rdv/updatable.rb
  app/models/concerns/rdvs_user/status_changeable.rb
  app/models/rdv.rb
Labels: tech, data.insertion, Interconnexion

#3089 Fix : `factories_spec.rb` se lance à chaque appel à `rspec`
  spec/models/factories_spec.rb
Labels: tech

#3074 Bug: milliers de notifs de rappel non envoyées si l'une plante
  app/jobs/cron_job.rb
  spec/jobs/cron_job/reminder_job_spec.rb
Labels: bug

#3073 feat(webhooks): Send webhooks for agents and agent_roles
  app/blueprints/agent_role_blueprint.rb
  app/models/agent.rb
  app/models/agent_role.rb
  app/models/webhook_endpoint.rb
Labels: data.insertion, Interconnexion

#3093 Gitignorer `docs/domain_model.svg` et le générer à la demande
  .gitignore
  Makefile
  docs/1-installation.md
  docs/4-notes-techniques.md
  docs/domain_model.svg
  lib/tasks/auto_generate_diagram.rake
Labels: tech

#3094 Bugfix: un agent peut passer un paramètre HTTP pour exporter une orga arbitraire
  app/controllers/admin/rdvs_controller.rb
  app/mailers/agents/export_mailer.rb
  spec/controllers/admin/rdvs_controller_spec.rb
  spec/mailers/agents/export_mailer_spec.rb
Labels: bug

#3087 :memo: Ajout d'une section de doc sur les pratiques de merge de PRs
  docs/2-contributions.md
Labels: tech, Documentation

#3066 Mise à jour vers Rails 7
  Gemfile
  Gemfile.lock
  app/views/layouts/mailer.html.slim
  app/views/layouts/super_admins/application.html.erb
  bin/rails
  bin/setup
  config/application.rb
  config/boot.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/cookie_rotator.rb
  config/initializers/cookies_serializer.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/initializers/inflections.rb
  config/initializers/new_framework_defaults_7_0.rb
Labels: tech

#3097 Mettre à jour les jours fériés de 2023
  app/helpers/users_helper.rb
  app/lib/lapin/range.rb
  app/models/creneau.rb
  app/services/off_days.rb
Labels: tech

#3080 API doc fine tuning
  .gitignore
  .rubocop.yml
  README.md
  docs/api/v1/description_api.md
  spec/rails_helper.rb
  spec/requests/api/v1/absences_request_spec.rb
  spec/requests/api/v1/agents_request_spec.rb
  spec/requests/api/v1/invitations_request_spec.rb
  spec/requests/api/v1/motifs_request_spec.rb
  spec/requests/api/v1/organisations_request_spec.rb
  spec/requests/api/v1/public_links_request_spec.rb
  spec/requests/api/v1/rdvs_request_spec.rb
  spec/requests/api/v1/user_profiles_request_spec.rb
  spec/requests/api/v1/users_request_spec.rb
  spec/support/api_spec_shared_examples.rb
  spec/swagger_helper.rb
  swagger/v1/api.json
Labels: tech, Interconnexion, Aides Jeunes, Documentation

#3103 Améliore le label d'un bouton
  app/views/admin/users/_duplicate_alert.html.slim
  spec/features/agents/users/agent_can_create_user_spec.rb
Labels:   ux  

#3099 Ajout d'un attr_reader sur rdv_base notifier
  app/controllers/users/rdvs_controller.rb
  app/models/concerns/rdv/updatable.rb
  app/models/concerns/rdvs_user/status_changeable.rb
  app/services/notifiers/rdv_base.rb
  app/services/notifiers/rdv_collectif_participations.rb
  spec/controllers/users/rdvs_controller_spec.rb
  spec/models/concerns/rdv/updatable_spec.rb
  spec/models/concerns/rdvs_user/status_changeable_spec.rb
  spec/services/notifiers/rdv_cancelled_spec.rb
  spec/services/notifiers/rdv_created_spec.rb
  spec/services/notifiers/rdv_upcoming_reminder_spec.rb
  spec/services/notifiers/rdv_updated_spec.rb
Labels: bug

#3109 Remontées 5xx sur les metrics Scalingo (requêtes PROPFIND)
  Gemfile
  Gemfile.lock
Labels: bug

#3098 Calcul de créneau : simplification de la manipulation des jours fériés
  app/models/rdv.rb
  app/services/concerns/users/creneaux_search_concern.rb
  app/services/next_availability_service.rb
  app/services/search_creneaux_for_agents_service.rb
  app/services/search_creneaux_without_lieu_for_agents_service.rb
  app/services/slot_builder.rb
  spec/services/slot_builder/busy_time_spec.rb
  spec/services/slot_builder_spec.rb
  spec/services/users/creneaux_search_spec.rb
Labels: tech

#3100 Organize technical documentation
  README.md
  app/views/common/_footer_users.html.slim
  docs/2-contributions.md
  docs/3-déploiement.md
  docs/api/webhooks/api-notifications-webhooks.md
  docs/api/webhooks/zimbra_01.png
  docs/api/webhooks/zimbra_02.png
  docs/api/webhooks/zimbra_03.png
Labels: Interconnexion, Documentation

#3106 Rafraichir le statuts du rdv aprés ajout/suppression d'un usager au rdv
  app/controllers/admin/participations_controller.rb
  app/models/rdv.rb
  app/models/rdvs_user.rb
  app/services/search_rdv_collectif.rb
  spec/factories/rdv.rb
  spec/factories/rdvs_user.rb
  spec/features/agents/rdvs_collectifs/editing_spec.rb
  spec/features/users/user_can_register_to_collective_rdv_spec.rb
  spec/models/rdv_spec.rb
  spec/models/rdvs_user_spec.rb
  spec/requests/users/participations_spec.rb
Labels: bug, RDV coté usager, RDV coté agent

#3110 Bugfix: certaines actions sur un RDV plantent quand un usager est soft deleted
  app/helpers/users_helper.rb
  app/models/rdvs_user.rb
  app/policies/agent/support_ticket_policy.rb
  app/policies/agent/user_note_policy.rb
  app/policies/agent/user_policy.rb
  spec/features/agents/agent_can_list_rdvs_spec.rb
Labels: bug

#3119 Factory RDV : timestamps trompeux
  spec/factories/rdv.rb
  spec/services/rdv_exporter_spec.rb
Labels: tech

#3120 Correcion de flaky spec sur les domaines utilisés par les mailers Devise
  spec/mailers/custom_devise_mailer_domain_spec.rb
Labels: tech

#3118 fix(user): Add organisation selection for motif without lieu
  app/controllers/search_controller.rb
  app/controllers/users/rdv_wizard_steps_controller.rb
  app/form_models/user_rdv_wizard.rb
  app/helpers/search_context_helper.rb
  app/services/search_context.rb
  app/views/search/_creneau_selection.html.slim
  app/views/search/_lieu_selection.html.slim
  app/views/search/_organisation_card_subtitles.html.slim
  app/views/search/_organisation_selection.html.slim
  app/views/search/_selected_motif_recap.html.slim
  spec/features/users/user_can_search_rdv_spec.rb
  spec/services/search_context_spec.rb
Labels: bug, Recherche de créneaux, RDV coté usager

#3062 Ajout doc : la vigie qualifie les remontées Sentry
  docs/5-role-de-vigie.md
Labels: tech, Documentation

#3124 Désactiver la cop `Rails/DynamicFindBy`
  .rubocop.yml
  app/controllers/api/v1/invitations_controller.rb
  app/controllers/concerns/token_invitable.rb
  app/controllers/users/invitations_controller.rb
Labels: tech

#3126 Crash lors de d'un déplacement de RDV (`range lower bound must be...`)
  app/controllers/users/rdvs_controller.rb
  app/models/creneau.rb
  app/services/next_availability_service.rb
  app/views/admin/creneaux/agent_searches/_lieu_search_results.html.slim
  app/views/admin/slots/_slots.html.slim
  app/views/common/_creneaux.html.slim
  app/views/search/_creneaux.html.slim
  app/views/users/rdvs/_creneaux.html.slim
  spec/controllers/users/rdvs_controller_spec.rb
Labels: bug

#3131 Documenation autour des `soft_delete`
  docs/decisions/2022-11-24-soft-delete-rdv-and-other.md
Labels: Documentation

#3123 feat(rdvs): Prise de rdv avec référent
  app/controllers/search_controller.rb
  app/controllers/users/rdv_wizard_steps_controller.rb
  app/form_models/user_rdv_wizard.rb
  app/helpers/search_context_helper.rb
  app/models/motif.rb
  app/services/concerns/users/creneaux_search_concern.rb
  app/services/search_context.rb
  app/services/users/creneaux_search.rb
  app/services/users/geo_search.rb
  app/views/search/_creneau_selection.html.slim
  app/views/search/_nothing_to_show.html.slim
  spec/features/users/user_can_search_rdv_spec.rb
  spec/services/search_context_spec.rb
  spec/services/search_rdv_collectif_spec.rb
  spec/services/users/creneaux_search_spec.rb
Labels: RDV coté usager
