Repository betagouv/rdv-service-public, pull requests merged in 2022-07, with the labels that each got.

#2582 Suppression de stats peu intéressante
  app/controllers/stats_controller.rb
  app/models/stat.rb
  app/views/admin/organisations/stats/index.html.slim
  app/views/stats/index.html.slim
  config/routes.rb
  spec/features/agents/admin_can_see_the_organisation_stats_spec.rb
  spec/features/anybody/anybody_can_see_stats_spec.rb
  spec/models/stat_spec.rb
Labels: Prévenir les référentes, a déployer lundi prochain

#2620 Ajout de statistique d'activation des agents
  app/helpers/stats_helper.rb
  app/views/stats/index.html.slim
Labels: Prévenir les référentes, À valider par l'équipe produit

#2617 Unification des écrans d'accueil
  app/controllers/lieux_controller.rb
  app/controllers/search_controller.rb
  app/controllers/users/rdv_wizard_steps_controller.rb
  app/controllers/welcome_controller.rb
  app/form_models/user_rdv_wizard.rb
  app/views/common/_search_form.html.slim
  app/views/search/_address_form.html.slim
  app/views/search/_banner.html.slim
  app/views/search/_creneau_selection.html.slim
  app/views/search/_creneaux.html.slim
  app/views/search/_lieu_selection.html.slim
  app/views/search/_motif_selection.html.slim
  app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim
  app/views/users/rdv_wizard_steps/step1.html.slim
  config/routes.rb
  spec/controllers/lieux_controller_spec.rb
  spec/controllers/welcome_controller_spec.rb
  spec/features/accessibility/welcome_pages_spec.rb
  spec/features/users/user_can_search_for_creneaux_spec.rb
  spec/features/users/user_can_search_rdv_spec.rb
  spec/form_models/user_rdv_wizard_spec.rb
Labels: À livrer lundi 18 juillet 2022

#2671 Mettre à jour Sentry JS de v6 à v7
  package.json
  yarn.lock
Labels: tech, javascript

#2677 Fix: charts défectueux si on charge la page avec Turbolinks
  app/views/admin/organisations/stats/index.html.slim
  app/views/admin/stats/index.html.slim
  app/views/common/_head.html.slim
  app/views/common/_head_agent.html.slim
  app/views/stats/index.html.slim
Labels: bug
