Repository betagouv/rdv-service-public, pull requests merged in 2022-10, with the labels that each got.

#2825 Paramétrage de la réservation en ligne
  app/controllers/admin/organisations/online_bookings_controller.rb
  app/helpers/agents_helper.rb
  app/helpers/online_bookings_helper.rb
  app/javascript/application_agent.js
  app/javascript/components/clipboard.js
  app/models/plage_ouverture.rb
  app/views/admin/organisations/online_bookings/_motif.html.slim
  app/views/admin/organisations/online_bookings/_plage_ouverture.html.slim
  app/views/admin/organisations/online_bookings/show.html.slim
  app/views/layouts/_left_menu.html.slim
  config/routes.rb
  spec/factories/agent.rb
  spec/features/agents/admin_can_configure_the_organisation_spec.rb
  spec/features/agents/agent_can_configure_online_booking_spec.rb
  spec/features/agents/agent_can_crud_motifs_spec.rb
  spec/helpers/online_bookings_helper_spec.rb
  spec/rails_helper.rb
  spec/requests/admin/organisations/online_bookings_spec.rb
  spec/support/devise_request_spec_helpers.rb
Labels: cnfs

#2857 Gestion d'un warning lorsqu'un motif dépasse la durée d'une plage d'ouverture
  app/helpers/plage_ouvertures_helper.rb
  app/models/plage_ouverture.rb
  app/views/admin/plage_ouvertures/_motifs_duration_exceed.html.slim
  app/views/admin/plage_ouvertures/_plage_ouverture.html.slim
  app/views/admin/plage_ouvertures/show.html.slim
Labels:   ux  

#2882 Permettre de retirer la catégorie d'un motif
  app/views/admin/motifs/_form.html.slim
Labels: bug

#2892 fix flacky test
  spec/features/agents/agent_can_configure_online_booking_spec.rb
Labels: bug, tech

#2879 feat(webhooks): Send webhooks for lieux
  app/blueprints/lieu_blueprint.rb
  app/models/lieu.rb
  app/models/webhook_endpoint.rb
Labels: data.insertion, Interconnexion

#2905 Bugfix: le graphique de stats de notifications n'est pas scopé au territoire sélectionné
  app/views/stats/index.html.slim
Labels: bug, .S, Statistiques

#2913 Corriger le crash de /public_api/public_links quand une org n'a pas d'external_id
  app/controllers/public_api/public_links_controller.rb
  app/models/plage_ouverture.rb
  spec/requests/public_api/public_links_spec.rb
Labels: bug

#2923 feat(view): Improve recap UI for invitations
  app/views/search/_creneau_selection.html.slim
  app/views/search/_lieu_selection.html.slim
  spec/features/accessibility/public_pages_spec.rb
Labels:   ux  , RDV coté usager

#2922 feat(search): Show available lieux only
  app/services/search_context.rb
  app/views/search/_lieu_selection.html.slim
  spec/features/users/user_can_be_invited_spec.rb
  spec/features/users/user_can_search_for_creneaux_spec.rb
Labels: RDV coté usager

#2860 Permettre la création de plages d'ouverture sans lieu
  app/controllers/admin/creneaux/agent_searches_controller.rb
  app/controllers/admin/slots_controller.rb
  app/controllers/users/rdvs_controller.rb
  app/form_models/user_rdv_wizard.rb
  app/helpers/agents_helper.rb
  app/helpers/lieux_helper.rb
  app/javascript/components/calendar.js
  app/models/creneau.rb
  app/models/motif.rb
  app/models/plage_ouverture.rb
  app/models/rdv.rb
  app/presenters/plage_ouverture_presenter.rb
  app/services/search_context.rb
  app/services/search_creneaux_for_agents_base.rb
  app/services/search_creneaux_for_agents_service.rb
  app/services/search_creneaux_without_lieu_for_agents_service.rb
  app/services/slot_builder.rb
  app/views/admin/agents/plage_ouvertures/index.json.jbuilder
  app/views/admin/creneaux/agent_searches/index.html.slim
  app/views/admin/plage_ouvertures/_form.html.slim
  app/views/admin/plage_ouvertures/_overlapping_plage_ouvertures.html.slim
  app/views/admin/plage_ouvertures/_plage_ouverture.html.slim
  app/views/admin/plage_ouvertures/show.html.slim
  app/views/admin/rdv_wizard_steps/step3.html.slim
  app/views/admin/slots/_slots.html.slim
  app/views/admin/slots/index.html.slim
  app/views/mailers/agents/plage_ouverture_mailer/_plage_ouverture_overview.html.slim
  app/views/search/_creneau_selection.html.slim
  app/views/search/_creneaux.html.slim
  app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim
  config/locales/fr.yml
  db/migrate/20220928093221_remove_plage_ouvertures_lieu_null_constraint.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/users/rdvs_controller_spec.rb
  spec/factories/plage_ouverture.rb
  spec/features/agents/agent_can_create_rdv_with_creneau_search_spec.rb
  spec/features/agents/agent_can_crud_plage_ouvertures_spec.rb
  spec/features/users/user_can_search_rdv_spec.rb
  spec/form_models/user_rdv_wizard_spec.rb
  spec/helpers/agents_helper_spec.rb
  spec/helpers/lieux_helper_spec.rb
  spec/models/creneau_spec.rb
  spec/models/motif_spec.rb
  spec/models/plage_ouverture_spec.rb
  spec/services/search_context_spec.rb
  spec/services/search_creneaux_for_agents_base_spec.rb
  spec/services/search_creneaux_for_agents_service_spec.rb
  spec/services/search_creneaux_without_lieu_for_agents_service_spec.rb
  spec/services/slot_builder_spec.rb
Labels: .S, Plages d'ouverture et indisponibilités

#2900 Téléchargement des rdvs par usager sur plusieurs organisations
  app/controllers/admin/rdvs_controller.rb
  app/controllers/admin/territories/agent_territorial_access_rights_controller.rb
  app/form_models/admin/rdv_search_form.rb
  app/mailers/agents/export_mailer.rb
  app/models/rdv.rb
  app/policies/agent/agent_policy.rb
  app/policies/configuration/territory_policy.rb
  app/services/rdvs_user_exporter.rb
  app/views/admin/rdvs/index.html.slim
  app/views/admin/territories/agents/edit.html.slim
  app/views/mailers/agents/export_mailer/rdvs_users_export.html.slim
  config/locales/fr.yml
  config/locales/models/agent.fr.yml
  config/locales/views/admin_territories_agents.yml
  config/routes.rb
  db/migrate/20221004125920_add_allow_to_download_metrics_to_agent_territorial_access_rights.rb
  db/schema.rb
  db/seeds.rb
  lsof
  spec/controllers/admin/rdvs_controller_spec.rb
  spec/form_models/admin/rdv_search_form_spec.rb
  spec/mailers/agents/export_mailer_spec.rb
  spec/mailers/previews/agents/export_mailer_preview.rb
  spec/policies/configuration/territory_policy_spec.rb
Labels: Statistiques

#2998 Perfs - Optimisation RAM exports de RDVs
  app/models/concerns/rdv/authored_concern.rb
  app/services/rdv_exporter.rb
  app/services/rdvs_user_exporter.rb
Labels: bug

#2994 document Agent API with rswag
  spec/requests/api/v1/agents_request_spec.rb
  spec/requests/api/v1/groups_request_spec.rb
  spec/requests/api/v1/organisations_request_spec.rb
  spec/requests/api/v1/organizations_request_spec.rb
  spec/swagger_helper.rb
  swagger/v1/api.json
Labels: Aides Jeunes

#2971 document User endpoints with rswag
  spec/requests/api/v1/agents_request_spec.rb
  spec/requests/api/v1/invitations_request_spec.rb
  spec/requests/api/v1/organisations_request_spec.rb
  spec/requests/api/v1/rdvs_request_spec.rb
  spec/requests/api/v1/users_request_spec.rb
  spec/swagger_helper.rb
  swagger/v1/api.json
Labels: Aides Jeunes

#2988 Utiliser les transactions Postgres dans les tests
  docs/bonnes-pratiques-de-tests.md
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/capybara_config.rb
Labels: tech

#2986 Cesser d'utiliser Sentry JS (beaucoup de bruit, très peu de signal)
  app/controllers/application_controller.rb
  app/javascript/application.js
  app/javascript/application_agent.js
  app/javascript/components/calendar.js
  app/javascript/components/sentry.js
  app/views/common/_env.html.erb
  package.json
  yarn.lock
Labels: tech

#2991 Reduce default and max elements per page in API
  app/controllers/api/v1/base_controller.rb
  docs/api/v1/description_api.md
  spec/requests/api/v1/groups_request_spec.rb
  spec/requests/api/v1/organisations_request_spec.rb
  spec/requests/api/v1/organizations_request_spec.rb
  spec/requests/api/v1/paginated_request_spec.rb
  spec/support/api_spec_macros.rb
  swagger/v1/api.json
Labels: Aides Jeunes
