Repository betagouv/rdv-service-public, pull requests merged in 2022-04, with the labels that each got.

#2336 Monitoring des SMS
  app/jobs/cron_job.rb
  app/models/rdv.rb
  app/models/receipt.rb
  app/models/user.rb
  app/services/sms_sender.rb
  app/sms/application_sms.rb
  app/sms/users/base_sms.rb
  app/views/admin/rdvs/show.html.slim
  app/views/admin/receipts/_receipt.html.slim
  app/views/admin/receipts/_receipts.html.slim
  app/views/admin/receipts/_resource_receipts_row.html.slim
  config/environments/development.rb
  config/locales/fr.yml
  config/locales/models/receipt.fr.yml
  config/locales/views/rdv.fr.yml
  db/migrate/20220406092227_create_receipts.rb
  db/schema.rb
  db/seeds.rb
  docs/domain_model.png
  scripts/sms_sender_test.rb
  spec/factories/receipt.rb
  spec/features/agents/agent_can_see_rdv_details_spec.rb
  spec/models/receipt_spec.rb
  spec/services/sms_sender_spec.rb
Labels: Démo

#2328 feat(rdv): add categories to motif
  app/blueprints/motif_blueprint.rb
  app/controllers/admin/motifs_controller.rb
  app/controllers/admin/territories/motif_fields_controller.rb
  app/controllers/api/v1/motifs_controller.rb
  app/models/motif.rb
  app/models/territory.rb
  app/policies/configuration/territory_policy.rb
  app/views/admin/motifs/_form.html.slim
  app/views/admin/motifs/show.html.slim
  app/views/admin/territories/motif_fields/edit.html.slim
  app/views/admin/territories/show.html.slim
  config/locales/models/motif.fr.yml
  config/locales/views/configuration.yml
  config/routes.rb
  db/migrate/20220408142133_add_category_field_to_motifs.rb
  db/schema.rb
  docs/domain_model.png
  spec/blueprint/rdv_blueprint_spec.rb
  spec/controllers/admin/territories/motif_fields_controller_spec.rb
  spec/factories/motif.rb
Labels: data.insertion, RDV coté agent, Démo

#2354 feat(motifs): allow to pass motif category when searching for a slot
  app/controllers/search_controller.rb
  app/services/search_context.rb
  spec/controllers/search_controller_spec.rb
Labels: data.insertion, RDV coté usager

#2375 fix(invitations): Choose matching motifs after filtering motifs
  app/services/search_context.rb
  spec/controllers/search_controller_spec.rb
  spec/services/search_context_spec.rb
Labels: data.insertion

#2380 fix(creneaux): Fix error when selecting a lieu
  app/services/next_availability_service.rb
  app/views/search/_lieu_selection.html.slim
Labels: bug

#2387 feat(seeds): ajouter des seeds pour rdv-insertion
  db/seeds.rb
Labels: data.insertion
