Repository betagouv/rdv-service-public, pull requests merged in 2022-09, with the labels that each got.

#2831 Bugfix : 3 copies du fichier ICS dans les mails de notifs
  app/mailers/concerns/ics_multipart_attached.rb
  spec/mailers/concerns/ics_multipart_attached_spec.rb
Labels: bug

#2817 Suppression de 'Détails Usager' dans la liste des RDV
  app/controllers/admin/rdvs_controller.rb
  app/form_models/admin/rdv_search_form.rb
  app/views/admin/agent_agendas/show.html.slim
  app/views/admin/rdvs/_rdv.html.slim
  app/views/admin/rdvs/_rdv_search_form.html.slim
  app/views/admin/rdvs/index.html.slim
  app/views/admin/rdvs_collectifs/index.html.slim
  spec/form_models/admin/rdv_search_form_spec.rb
Labels:   ux  , RDV coté agent

#2839 Envoyer des webhooks pour les motifs
  app/blueprints/motif_blueprint.rb
  app/models/motif.rb
  app/models/webhook_endpoint.rb
  app/views/admin/territories/webhook_endpoints/_form.html.slim
Labels: data.insertion, Interconnexion

#2837 fix-2826: dédoublonne les agents sur les statistiques
  app/controllers/stats_controller.rb
  app/models/territory.rb
  spec/models/territory_spec.rb
Labels: bug, Good First Issue, -26, Statistiques, MedSoc

#2854 Hotfix: motif-form.js
  app/javascript/components/motif-form.js
Labels: bug

#2858 [RDV-I] Ajout d'une catégorie de motif pour les RDVs de suivi RSA
  app/models/motif.rb
  config/locales/models/motif.fr.yml
  db/migrate/20220927160954_add_rsa_follow_up_motif_category.rb
  db/schema.rb
  docs/domain_model.svg
Labels: data.insertion

#2848 Motif: Affichage conditionné pour les prises de RDV en ligne
  app/helpers/motifs_helper.rb
  app/javascript/components/motif-form.js
  app/javascript/stylesheets/components/_utilities.scss
  app/views/admin/motifs/_form.html.slim
  app/views/admin/motifs/show.html.slim
  spec/features/agents/agent_can_crud_motifs_spec.rb
Labels:   ux  
