Repository betagouv/rdv-service-public, pull requests merged in 2022-12, with the labels that each got.

#3039 Ajoute un parcours pour les RDV sur des motifs de suivi pour l'usager
  app/helpers/search_context_helper.rb
  app/services/search_context.rb
  app/views/search/_motif_selection.html.slim
  app/views/search/_service_selection.html.slim
  app/views/users/rdvs/index.html.slim
  spec/features/accessibility/public_pages_spec.rb
  spec/features/agents/agent_can_test_online_booking_spec.rb
  spec/features/users/user_can_search_rdv_spec.rb
  spec/requests/prendre_rdv_spec.rb
Labels: bug

#3138 feat(api): Assign user referent through API
  .rubocop.yml
  app/blueprints/referent_assignation_blueprint.rb
  app/controllers/admin/referent_assignations_controller.rb
  app/controllers/admin/users_controller.rb
  app/controllers/api/v1/referent_assignations_controller.rb
  app/models/agent.rb
  app/models/organisation.rb
  app/models/referent_assignation.rb
  app/models/user.rb
  app/models/webhook_endpoint.rb
  app/policies/agent/referent_assignation_policy.rb
  app/views/admin/referent_assignations/index.html.slim
  app/views/admin/users/show.html.slim
  app/views/mailers/common/_rdv_overview.html.slim
  config/locales/models/referent_assignation.fr.yml
  config/routes.rb
  config/routes/api.rb
  db/migrate/20221129104727_rename_agents_users_to_referent_assignations.rb
  db/schema.rb
  spec/controllers/admin/referent_assignations_controller_spec.rb
  spec/factories/referent_assignation.rb
  spec/requests/api/v1/referent_assignations_request_spec.rb
  spec/swagger_helper.rb
  swagger/v1/api.json
Labels: Interconnexion

#3149 Ne pas ré-envoyer de mail d'invtation aux CNFS existants lors de l'import
  scripts/import_conseillers_numeriques.rb
Labels: cnfs

#3148 Utiliser des sous-requêtes SQL plutôt que de passer des listes d'IDs
  app/controllers/admin/rdvs_controller.rb
  app/controllers/api/v1/public_links_controller.rb
  app/mailers/agents/export_mailer.rb
  app/models/agent.rb
  app/models/application_record.rb
  app/models/motif.rb
  app/policies/agent/absence_policy.rb
  app/policies/agent/agent_policy.rb
  app/services/users/geo_search.rb
  docs/2-contributions.md
Labels: tech

#3146 Diviser `seeds.rb` en 3 fichiers : medico-social, RDV-Insertion, CNFS
  db/seeds.rb
  db/seeds/cnfs.rb
  db/seeds/medico_social.rb
  db/seeds/rdv_insertion.rb
Labels: tech

#3150 feat(webhooks): Add follow_up attribute to motif blueprint
  app/blueprints/motif_blueprint.rb
Labels: data.insertion, Interconnexion

#3147 Éviter que la spec sur l'allocation mémoire soit flaky
  config/environments/test.rb
  spec/features/allocation_for_search_context_spec.rb
Labels: tech

#3172 Utiliser `pluralize` à la place de "(s)"
  app/views/admin/rdvs/_rdv_details.html.slim
  app/views/mailers/common/_rdv_overview.html.slim
  app/views/stats/index.html.slim
Labels:   ux  

#3159 Modification de l'explication d'inclusion connect
  app/views/common/_inclusionconnect_button.html.slim
Labels:   ux  

#3142 Affiche quels RDV peuvent être vues par l'agent
  app/policies/agent/rdv_policy.rb
  app/views/admin/agent_agendas/show.html.slim
  app/views/admin/rdvs/_rdv_visibility.html.slim
  app/views/admin/rdvs/index.html.slim
  app/views/admin/users/show.html.slim
Labels:   ux  , -62, RDV coté agent

#3171 Éviter le message de dépréciation sur `ActiveRecord::Base.default_timezone`
  Gemfile
  Gemfile.lock
Labels: tech

#3156 fix(api): Render not_found when user does not belong to org
  app/controllers/api/v1/users_controller.rb
  spec/requests/api/v1/users_request_spec.rb
Labels: data.insertion, Interconnexion

#3173 Migration vers Sentry de l'incubateur beta
  .env.sample
  app/controllers/admin/rdvs_controller.rb
  app/controllers/inclusion_connect_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/controllers/users/rdvs_controller.rb
  config/initializers/content_security_policy.rb
  docs/0-docs.md
  docs/5-role-de-vigie.md
  docs/decisions/2022-12-12-migrer-sentry-vers-instance-incubateur-beta.md
Labels: tech, Documentation

#3177 Factory de RDV sans usager : cesser de créer un usager pour rien
  spec/factories/rdv.rb
Labels: tech

#3176 Permettre aux prescripteurs de réserver des RDVs collectifs
  app/controllers/concerns/can_have_rdv_wizard_context.rb
  app/controllers/prescripteur_rdv_wizard_controller.rb
  app/form_models/prescripteur_rdv_wizard.rb
  db/seeds/cnfs.rb
  db/seeds/medico_social.rb
  spec/features/prescripteurs/can_add_a_user_to_a_rdv_collectif_spec.rb
Labels: cnfs

#3174 Montrer les prochaines disponibilités par organisation
  app/services/search_context.rb
  app/views/search/_organisation_selection.html.slim
  spec/features/users/user_can_search_rdv_spec.rb
Labels: Recherche de créneaux, RDV coté usager

#3188 Amélioration rapide de la page d'accueil de rdv-aide-numerique.fr
  app/views/search/address_selection/_rdv_aide_numerique.html.slim
  app/views/search/banners/_rdv_aide_numerique.html.slim
Labels: .S, cnfs

#2982 Ignorer les jobs de mailers qui ne trouvent pas la plage / absence
  app/mailers/application_mailer.rb
  app/mailers/custom_mailer_delivery_job.rb
  spec/jobs/custom_mailer_delivery_job_spec.rb
Labels: tech

#3213 Toujours montrer la page du choix de service lorsqu'il y en a plusieurs
  app/services/search_context.rb
  spec/features/users/user_can_search_rdv_spec.rb
  spec/services/search_context_spec.rb
Labels: bug, RDV coté usager

#3215 Affiche collectif ou suivi sur la liste RDV usager
  app/views/admin/rdvs/_short_rdv.html.slim
Labels:   ux  , .S, RDV coté agent, RDV Collectif

#3214 Ajoute la clef et traduction pour le responsible
  config/locales/models/attributes.fr.yml
Labels: bug, .S

#3216 Utilise l'action index plutôt que search pour Teams
  app/controllers/admin/territories/teams_controller.rb
  app/views/admin/creneaux/agent_searches/index.html.slim
  app/views/admin/territories/teams/index.json.jbuilder
  config/routes.rb
  spec/controllers/admin/territories/teams_controller_spec.rb
  spec/requests/admin/territories/cruds_teams_configuration_spec.rb
Labels: tech, .S
