Repository betagouv/rdv-service-public, pull requests merged in 2022-03, with the labels that each got.

#2230 Supprime le lien de téléchargement de statistique personnel
  app/views/admin/stats/index.html.slim
Labels: Démo

#2262 Onboarding spéficique aux CNFS
  app/controllers/admin/organisations/setup_checklists_controller.rb
  app/views/admin/organisations/setup_checklists/show.slim
  app/views/admin/organisations/setup_checklists/show_conseiller_numerique.slim
Labels: cnfs

#2253 Empeche acces file attente pour motif non reservable en ligne
  app/models/rdv.rb
  spec/factories/rdv.rb
  spec/models/rdv_spec.rb
Labels: bug, -83

#2273 Renseigne le tel avant le mail dans la fiche usager
  app/views/admin/users/_responsible_form_fields.html.slim
Labels: -83

#2279 Paramètre l'affichage du contexte d'un RDV
  app/controllers/admin/territories/rdv_fields_controller.rb
  app/models/territory.rb
  app/policies/configuration/territory_policy.rb
  app/views/admin/rdv_wizard_steps/step2.html.slim
  app/views/admin/rdvs/_rdv.html.slim
  app/views/admin/rdvs/_rdv_details.html.slim
  app/views/admin/rdvs/_short_rdv.html.slim
  app/views/admin/territories/rdv_fields/edit.html.slim
  app/views/admin/territories/show.html.slim
  config/locales/views/configuration.yml
  config/locales/views/rdv.fr.yml
  config/routes.rb
  db/migrate/20220317141436_add_enable_context_field_to_territory.rb
  db/schema.rb
  spec/controllers/admin/territories/rdv_fields_controller_spec.rb
  spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
Labels: Démo

#2250 Permet de créer des lieux ponctuels pour un RDV
  app/controllers/admin/lieux_controller.rb
  app/controllers/admin/rdv_wizard_steps_controller.rb
  app/form_models/concerns/admin/rdv_wizard_form_concern.rb
  app/helpers/lieux_helper.rb
  app/helpers/rdvs_helper.rb
  app/models/lieu.rb
  app/models/plage_ouverture.rb
  app/models/rdv.rb
  app/views/admin/lieux/_form.html.slim
  app/views/admin/lieux/_lieu.html.slim
  app/views/admin/lieux/_lieu_fields.html.slim
  app/views/admin/lieux/edit.html.slim
  app/views/admin/lieux/new.html.slim
  app/views/admin/plage_ouvertures/_plage_ouverture.html.slim
  app/views/admin/plage_ouvertures/show.html.slim
  app/views/admin/rdv_wizard_steps/_hidden_fields.html.slim
  app/views/admin/rdv_wizard_steps/step1.html.slim
  app/views/admin/rdv_wizard_steps/step2.html.slim
  app/views/admin/rdv_wizard_steps/step3.html.slim
  app/views/admin/rdv_wizard_steps/step4.html.slim
  app/webpacker/components/rdv_lieu.js
  app/webpacker/packs/application_agent.js
  config/brakeman.ignore
  config/locales/admin_rdv_wizard_form.fr.yml
  config/locales/models/lieu.fr.yml
  config/locales/models/plage_ouverture.fr.yml
  config/locales/models/rdv.fr.yml
  config/locales/views/admin_lieux.fr.yml
  db/migrate/20220321113311_add_lieu_single_use.rb
  db/schema.rb
  db/seeds.rb
  docs/domain_model.png
  spec/factories/lieu.rb
  spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
  spec/models/lieu_spec.rb
  spec/models/plage_ouverture_spec.rb
  spec/models/rdv_spec.rb
Labels: Démo

#2197 refactor(invitations): Revamp invited user journey[4/4]
  .rubocop.yml
  app/controllers/admin/rdvs_controller.rb
  app/controllers/concerns/token_invitable.rb
  app/controllers/users/rdvs_controller.rb
  app/mailers/users/file_attente_mailer.rb
  app/mailers/users/rdv_mailer.rb
  app/models/concerns/payloads/rdv.rb
  app/models/file_attente.rb
  app/models/rdv.rb
  app/models/rdvs_user.rb
  app/models/user.rb
  app/policies/user/rdv_policy.rb
  app/services/notifiers/rdv_base.rb
  app/services/notifiers/rdv_cancelled.rb
  app/services/notifiers/rdv_created.rb
  app/services/notifiers/rdv_date_updated.rb
  app/services/notifiers/rdv_upcoming_reminder.rb
  app/services/rdv_updater.rb
  app/sms/users/base_sms.rb
  app/sms/users/file_attente_sms.rb
  app/sms/users/rdv_sms.rb
  app/views/mailers/agents/rdv_mailer/rdv_date_updated.html.slim
  app/views/mailers/common/_rdv_cancellable.html.slim
  app/views/mailers/users/file_attente_mailer/new_creneau_available.html.slim
  app/views/mailers/users/rdv_mailer/rdv_cancelled.html.slim
  app/views/mailers/users/rdv_mailer/rdv_created.html.slim
  app/views/mailers/users/rdv_mailer/rdv_date_updated.html.slim
  app/views/mailers/users/rdv_mailer/rdv_upcoming_reminder.html.slim
  app/views/users/rdvs/_rdv.html.slim
  config/routes.rb
  db/migrate/20220225075042_devise_invitable_add_to_rdvs_users.rb
  db/migrate/20220309133231_add_show_token_in_sms_to_organisations.rb
  db/schema.rb
  docs/domain_model.png
  spec/controllers/concerns/token_invitable_spec.rb
  spec/controllers/users/rdvs_controller_spec.rb
  spec/factories/rdvs_user.rb
  spec/features/users/user_can_be_invited_spec.rb
  spec/features/users/user_can_search_rdv_spec.rb
  spec/mailers/users/rdv_mailer_spec.rb
  spec/models/file_attente_spec.rb
  spec/models/rdv_spec.rb
  spec/services/notifiers/rdv_cancelled_spec.rb
  spec/services/notifiers/rdv_created_spec.rb
  spec/services/notifiers/rdv_date_updated_spec.rb
  spec/services/notifiers/rdv_upcoming_reminder_spec.rb
  spec/services/rdv_updater_spec.rb
  spec/sms/users/base_sms_spec.rb
  spec/sms/users/file_attente_sms_spec.rb
  spec/sms/users/rdv_sms_spec.rb
Labels: Démo

#2314 Script d'import des cnfs pour la phase 4
  app/mailers/custom_devise_mailer.rb
  app/views/devise/mailer/invitation_instructions_cnfs.html.erb
  app/views/devise/mailer/invitation_instructions_cnfs.text.erb
  config/locales/devise.fr.yml
  scripts/import_conseillers_numeriques.rb
Labels: cnfs
