Repository betagouv/rdv-service-public, pull requests merged in 2023-03, with the labels that each got.

#3377 Mettre à jour la stack Scalingo (de `scalingo-18` à `scalingo-22`)
  scalingo.json
Labels: tech

#3368 feat(api): Ajout d'un endpoint pour updater les organisations
  app/controllers/api/v1/organisations_controller.rb
  app/policies/agent/organisation_policy.rb
  config/routes/api.rb
  spec/requests/api/v1/organisations_request_spec.rb
  spec/swagger_helper.rb
  swagger/v1/api.json
Labels: data.insertion, Interconnexion

#3407 Corriger l'heure de nettoyage des salles d'attente + cron à heure locale
  config/initializers/good_job.rb
Labels: tech

#3410 Correction du crash de FileAttenteJob
  app/models/rdv.rb
Labels: Bug 🔴

#3411 Correction d'un test qui échoue au changement d'heure
  spec/requests/api/v1/users_request_spec.rb
Labels: tech

#3423 Bugfix: les RDVs ne sont pas ordonnés proprement au sein de chaque page
  app/controllers/admin/rdvs_controller.rb
Labels: Bug 🔴
