Repository betagouv/rdv-service-public, pull requests merged in 2023-02, with the labels that each got.

#3303 Bugfix: mettre à jour l'expression CRON en base lorsqu'elle change dans le code
  app/jobs/cron_job.rb
Labels: tech

#3311 Patch la création d'usager combiné
  app/views/admin/users/_responsible_form_wrapper.html.slim
  spec/features/agents/agent_can_create_relative_and_responsible_spec.rb
Labels: bug

#3308 Renommer une méthode de helper au nom ambigu
  app/helpers/motifs_helper.rb
  app/views/admin/creneaux/agent_searches/index.html.slim
  app/views/admin/rdv_wizard_steps/step2.html.slim
  app/views/admin/rdv_wizard_steps/step3.html.slim
  app/views/admin/rdv_wizard_steps/step4.html.slim
  app/views/admin/rdvs_collectifs/index.html.slim
  app/views/admin/territories/sectorisation_tests/_attribution.html.slim
  app/views/admin/territories/sectorisation_tests/search.html.slim
  app/views/search/_creneau_selection.html.slim
  app/views/search/_selected_motif_recap.html.slim
Labels: tech

#3306 fix(webhook): Trigger webhook when agent removed from org
  app/models/agent.rb
  app/models/organisation.rb
  app/services/agent_removal.rb
  spec/services/agent_removal_spec.rb
Labels: Interconnexion

#3318 Ajouter une clé étrangère sur `sector_attributions.organisation_id`
  db/migrate/20230206135816_add_foreign_key_to_sector_attributions_organisation_id.rb
  db/schema.rb
Labels: bug, tech

#3359 Correction flaky tests causés par IDs codés en dur
  spec/jobs/outlook/create_event_job_spec.rb
  spec/jobs/outlook/destroy_event_job_spec.rb
  spec/jobs/outlook/mass_create_event_job_spec.rb
  spec/jobs/outlook/mass_destroy_event_job_spec.rb
  spec/jobs/outlook/update_event_job_spec.rb
  spec/models/concerns/outlook/synchronizable_spec.rb
  spec/models/outlook/event_spec.rb
Labels: tech

#3333 Renommer la table `agents_organisations` en `agent_roles` pour cohérence avec le modèle
  app/models/agent_role.rb
  db/migrate/20230213175430_rename_agent_organisations_to_agent_role.rb
  db/schema.rb
  scripts/full_orga_sql_dump.sh
Labels: tech

#3361 Réparer la CI qui échoue au build JS (`envelope routines::unsupported`)
  .github/workflows/ci.yml
  .gitignore
  .node-version
Labels: tech

#3348 N'affiche pas les badges de suppression si non nécessaire
  app/helpers/users_helper.rb
Labels: Bug 🔴

#3372 Liste les usagers unique d'un territoire
  app/policies/agent/user_policy.rb
  app/views/admin/users/search.json.jbuilder
  spec/features/agents/users/users_spec.rb
Labels: Bug 🔴
