Repository betagouv/rdv-service-public, pull requests merged in 2023-01, with the labels that each got.

#3224 Utilise l'`index` du `Admin::TeamsController`
  app/views/admin/territories/agents/edit.html.slim
Labels: bug, tech

#3217 Utilise le format date des navigateurs
  app/helpers/application_helper.rb
  app/javascript/application.js
  app/javascript/application_agent.js
  app/javascript/components/datetimepicker.js
  app/javascript/components/recurrence-form.js
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/application_agent.scss
  app/views/admin/creneaux/agent_searches/index.html.slim
  app/views/admin/rdv_wizard_steps/step3.html.slim
  app/views/admin/rdvs/_rdv_search_form.html.slim
  app/views/admin/rdvs/edit.html.slim
  app/views/admin/rdvs_collectifs/index.html.slim
  app/views/admin/rdvs_collectifs/new.html.slim
  app/views/admin/users/_form.html.slim
  app/views/admin/users/_responsible_form_fields.html.slim
  app/views/common/_recurrence.html.slim
  app/views/users/relatives/_form_fields.html.slim
  app/views/users/users/_form.html.slim
  spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
  spec/features/agents/agent_can_manage_recurrence_on_plage_ouverture_spec.rb
  spec/features/agents/rdvs_collectifs/full_lifecycle_spec.rb
Labels:   ux  

#3254 #3247 Bug : l'e-mail de création de compte usager est toujours envoyé au domaine RDV Solidarité
  app/controllers/admin/users_controller.rb
  app/controllers/users/registrations_controller.rb
  app/form_models/prescripteur_rdv_wizard.rb
  app/mailers/custom_devise_mailer.rb
  app/mailers/prescripteur_mailer.rb
  app/models/concerns/rdv/using_waiting_room.rb
  app/models/concerns/user/devise_invitable_with_domain.rb
  app/models/domain.rb
  app/models/user.rb
  config/application.rb
  db/seeds/cnfs.rb
  spec/features/agents/users/agent_can_create_user_spec.rb
  spec/features/users/user_can_use_link_to_take_rdv_in_organisation_spec.rb
  spec/features/users/user_signs_up_and_signs_in_spec.rb
Labels: bug

#3253 Ruby 3.2.0
  .github/workflows/ci.yml
  .ruby-version
  Gemfile
  Gemfile.lock
  docker/job/Dockerfile
  docker/script/Dockerfile
  docker/web/Dockerfile
  spec/jobs/cron_job/reminder_job_spec.rb
  spec/jobs/custom_mailer_delivery_job_spec.rb
Labels: tech

#3260 Recherche une équipe
  app/controllers/admin/territories/teams_controller.rb
  app/views/admin/territories/teams/index.html.slim
  spec/requests/admin/territories/cruds_teams_configuration_spec.rb
Labels: bug

#3273 Update Rails from 7.0.4 to 7.0.4.1 for security
  Gemfile.lock
Labels: tech

#3274 Mise à jour de la gem `mail` qui était fixée en version RC
  Gemfile
  Gemfile.lock
Labels: tech

#3275 Ajout de 2 nouvelles catégories de motifs
  app/models/concerns/motif/category.rb
  config/locales/models/motif.fr.yml
  db/migrate/20230119140851_add_rsa_atelier_competences_and_rsa_atelier_rencontres_pro_to_motif_category.rb
  db/schema.rb
Labels: data.insertion

#3279 Fix scalingo_dump.sh
  scripts/scalingo_dump.sh
Labels: tech

#2909 Rappatrie les champs `notes` et `logement` dans la table `users`
  app/blueprints/user_blueprint.rb
  app/blueprints/user_profile_blueprint.rb
  app/controllers/admin/users_controller.rb
  app/form_models/merge_users_form.rb
  app/helpers/users_helper.rb
  app/models/user.rb
  app/services/merge_users_service.rb
  app/views/admin/merge_users/_user_notes.html.slim
  app/views/admin/merge_users/new.html.slim
  app/views/admin/rdvs_users/_user_card.html.slim
  app/views/admin/rdvs_users/_user_details.html.slim
  app/views/admin/users/_form.html.slim
  app/views/admin/users/_responsible_form_fields.html.slim
  app/views/admin/users/_responsible_information.html.slim
  app/views/admin/users/show.html.slim
  app/views/users/users/_form.html.slim
  config/locales/models/user.fr.yml
  config/locales/models/user_profile.fr.yml
  db/migrate/20221007122950_add_logement_and_note_to_users.rb
  db/schema.rb
  spec/factories/user.rb
  spec/factories/user_profile.rb
  spec/features/agents/users/agent_can_merge_users_spec.rb
  spec/features/agents/users/agent_can_update_user_spec.rb
  spec/models/user_spec.rb
  spec/requests/api/v1/user_profiles_request_spec.rb
  spec/requests/api/v1/users_request_spec.rb
  spec/services/merge_users_service_spec.rb
  spec/swagger_helper.rb
Labels: tech, Fiche usager

#3223 Déplace la gestion du droit d'admin de territoire
  app/controllers/admin/territories/agent_territorial_roles_controller.rb
  app/controllers/admin/territories/agents_controller.rb
  app/controllers/admin/territories_controller.rb
  app/models/agent.rb
  app/models/concerns/can_have_territorial_access.rb
  app/policies/configuration/agent_policy.rb
  app/views/admin/territories/agent_territorial_roles/index.html.slim
  app/views/admin/territories/agents/edit.html.slim
  app/views/admin/territories/edit.html.slim
  app/views/admin/territories/show.html.slim
  app/views/layouts/application_agent_departement.html.slim
  config/locales/views/configuration.yml
  config/routes.rb
  spec/controllers/admin/territories/agent_territorial_roles_controller_spec.rb
  spec/controllers/admin/territories_controller_spec.rb
  spec/features/agents/admin_can_configure_the_territory_spec.rb
  spec/models/concerns/can_have_territorial_access_spec.rb
Labels: Configuration

#3294 Améliorer les perfs de la liste des RDVs (janvier 2023)
  app/controllers/admin/rdvs_controller.rb
  app/controllers/agent_auth_controller.rb
  app/models/user.rb
  app/views/admin/rdvs/index.html.slim
Labels: tech

#3277 Clarifier le bouton d'import d'usager dans un organisation
  app/views/admin/users/_duplicate_alert.html.slim
  spec/features/agents/users/agent_can_create_user_spec.rb
  spec/form_models/admin/user_form_spec.rb
Labels:   ux  

#3295 Mise à jour de la gem launchy
  Gemfile.lock
Labels: tech

#3280 Supprimer les configs Docker
  .github/workflows/push-docker-image-branch.yml
  .github/workflows/push-docker-image-tags.yml
  docker-compose.yml
  docker/job/Dockerfile
  docker/script/Dockerfile
  docker/web/Dockerfile
Labels: tech

#3289 feat(api): Add delete user_profile endpoint
  app/controllers/api/v1/user_profiles_controller.rb
  app/policies/agent/user_profile_policy.rb
  config/routes/api.rb
  spec/requests/api/v1/user_profiles_request_spec.rb
  swagger/v1/api.json
Labels: data.insertion, Interconnexion

#3286 Envoyer les rappels (SMS et e-mail) chaque heure, plutôt qu'à 9h chaque jour
  app/jobs/cron_job.rb
  app/models/rdv.rb
  spec/jobs/cron_job/reminder_job_spec.rb
Labels: tech

#3300 Notifs de rappel : utiliser une stratégie de scheduling plus solide
  app/jobs/cron_job.rb
  app/jobs/rdv_upcoming_reminder_job.rb
  app/models/rdv.rb
  spec/jobs/cron_job/reminder_job_spec.rb
Labels: tech
