Repository betagouv/rdv-service-public, pull requests merged in 2023-06, with the labels that each got.

#3595 Présélectionner le lieu si il y en a qu'un dans les plages d'ouvertures
  app/views/admin/plage_ouvertures/_form.html.slim
Labels:   ux  

#3583 Définir les add-ons des review apps explicitement dans scalingo.json
  scalingo.json
Labels: tech

#3629 Refacto du traitement des token d'invitations
  app/controllers/concerns/token_invitable.rb
  app/controllers/search_controller.rb
  app/controllers/user_auth_controller.rb
  app/controllers/users/rdv_wizard_steps_controller.rb
  app/controllers/users/rdvs_controller.rb
  app/controllers/users/user_name_initials_verification_controller.rb
  app/form_models/user_rdv_wizard.rb
  app/models/invitation.rb
  app/models/user.rb
  app/services/search_context.rb
  app/views/search/_creneau_selection.html.slim
  app/views/search/_creneaux.html.slim
  app/views/search/_lieu_selection.html.slim
  app/views/search/_motif_selection.html.slim
  app/views/search/_organisation_selection.html.slim
  app/views/search/_rdv_collectif.html.slim
  app/views/search/_selected_motif_recap.html.slim
  app/views/search/_service_selection.html.slim
  config/locales/devise.fr.yml
  spec/controllers/concerns/token_invitable_spec.rb
  spec/controllers/search_controller_spec.rb
  spec/controllers/users/rdv_wizard_steps_controller_spec.rb
  spec/controllers/users/rdvs_controller_spec.rb
  spec/controllers/users/user_name_initials_verification_controller_spec.rb
  spec/features/accessibility/public_pages_spec.rb
  spec/features/allocation_for_search_context_spec.rb
  spec/features/users/user_can_be_invited_spec.rb
  spec/features/users/user_can_manage_collective_rdv_spec.rb
  spec/services/search_context_spec.rb
Labels: RDV coté usager

#3630 Supprimer les jobs une semaine après leur exécution (à la place de 2 semaines)
  config/initializers/good_job.rb
Labels: tech
