Repository betagouv/rdv-service-public, pull requests merged in 2024-12, with the labels that each got.

#4835 Passage de l'interface des agents aux couleurs du dsfr
  app/assets/images/logos/logo_sombre_aide_numerique.svg
  app/assets/images/logos/logo_sombre_rdv_service_public.svg
  app/assets/images/logos/logo_sombre_solidarites.svg
  app/helpers/application_helper.rb
  app/javascript/stylesheets/_variables.scss
  app/javascript/stylesheets/application_agent.scss
  app/javascript/stylesheets/components/_cards.scss
  app/javascript/stylesheets/structure/_authentication.scss
  app/javascript/stylesheets/structure/_left-menu.scss
  app/views/admin/agent_agendas/show.html.slim
  app/views/admin/rdvs/index.html.slim
  app/views/admin/users/index.html.slim
  app/views/agents/_preferences_menu.html.slim
  app/views/layouts/_left_menu.html.slim
  app/views/layouts/application_agent_config.html.slim
  app/views/search/_motif_selection.html.slim
Labels: DSFR

#4852 Passage des flashes au DSFR sur l'interface agent
  app/controllers/admin/absences_controller.rb
  app/controllers/admin/agent_intervenants_controller.rb
  app/controllers/admin/agents_controller.rb
  app/controllers/admin/invitations_controller.rb
  app/controllers/admin/lieux_controller.rb
  app/controllers/admin/motifs_controller.rb
  app/controllers/admin/organisations_controller.rb
  app/controllers/admin/participations_controller.rb
  app/controllers/admin/plage_ouvertures_controller.rb
  app/controllers/admin/rdvs_collectifs_controller.rb
  app/controllers/admin/rdvs_controller.rb
  app/controllers/admin/territories/agent_roles_controller.rb
  app/controllers/admin/users_controller.rb
  app/form_models/admin/rdv_wizard_form/step4.rb
  app/javascript/stylesheets/application_agent.scss
  app/javascript/stylesheets/structure/_left-menu.scss
  app/views/common/_head_agent.html.slim
  app/views/layouts/_left_menu.html.slim
  app/views/layouts/application_agent.html.slim
  spec/controllers/admin/agent_intervenants_controller_spec.rb
  spec/controllers/admin/rdv_wizard_steps_controller_spec.rb
  spec/controllers/admin/rdvs_collectifs_controller_spec.rb
Labels: a11y, DSFR

#4860 Stepper DSFR pour la création de rdv côté agent
  app/controllers/admin/rdv_wizard_steps_controller.rb
  app/views/admin/rdv_wizard_steps/_card.html.slim
  app/views/admin/rdv_wizard_steps/step1.html.slim
  app/views/admin/rdv_wizard_steps/step2.html.slim
  app/views/admin/rdv_wizard_steps/step3.html.slim
  app/views/admin/rdv_wizard_steps/step4.html.slim
  app/views/common/_stepper.html.slim
  app/views/layouts/_rdv_a_renseigner.html.slim
  config/locales/admin_rdv_wizard_form.fr.yml
  spec/features/agents/agent_can_create_rdv_with_wizard_spec.rb
  spec/features/agents/rdv_wizard/step4_spec.rb
  spec/features/agents/rdvs_collectifs/agent_can_create_rdv_collectif_spec.rb
Labels: DSFR

#4878 Correctif pour les icônes de lien externes en double
  app/views/admin/creneaux_search/_prescription_cta.html.slim
  app/views/admin/motifs/form/_notifs_et_instructions.html.slim
  app/views/admin/motifs/form/_resa_en_ligne.html.slim
  app/views/admin/rdvs/_rdv_details.html.slim
  app/views/admin/static_pages/support.html.slim
  app/views/admin/territories/zone_imports/new.html.slim
  app/views/admin/territories/zones/_form.html.slim
  app/views/layouts/_agent_footer.html.slim
  app/views/prescripteur_rdv_wizard/new_prescripteur.html.slim
  app/views/search/_nothing_to_show_contactable_organisation.html.slim
  app/views/users/registrations/pending.html.slim
  config/locales/models/motif.fr.yml
Labels: DSFR

#4876 Ajout du DSFR dans l'interface de configuration des agents
  app/controllers/agents/mot_de_passes_controller.rb
  app/controllers/agents/outlook_sync_controller.rb
  app/controllers/agents/preferences_controller.rb
  app/controllers/agents/webcal_sync_controller.rb
  app/controllers/omniauth_callbacks_controller.rb
  app/javascript/application_agent_config.js
  app/javascript/fonts/lato-v17-latin-regular.woff
  app/javascript/fonts/lato-v17-latin-regular.woff2
  app/javascript/stylesheets/_fonts.scss
  app/javascript/stylesheets/application_agent_config.scss
  app/javascript/stylesheets/structure/_misc.scss
  app/views/agents/preferences/show.html.slim
  app/views/agents/sessions/new.html.slim
  app/views/layouts/application_agent_config.html.slim
  spec/features/agents/account/agent_can_login_spec.rb
  spec/features/agents/account/agent_session_expires_spec.rb
  spec/features/agents/oauth_provider_spec.rb
  spec/features/agents/track_broken_links_spec.rb
Labels: DSFR

#4885 Passage du flash de l'espace admin au dsfr, et suppression d'une vieille bannière
  app/views/admin/agents/_cnfs_email_change_banner.html.slim
  app/views/layouts/application_agent.html.slim
  app/views/layouts/application_configuration.html.slim
Labels: DSFR

#4888 Mise à jour de la déclaration d’accessibilité
  app/views/static_pages/accessibility.html.slim
Labels: a11y

#4884 Mise à jour du DSFR sur la version 1.13
  app/helpers/application_helper.rb
  package.json
  public/dsfr-v1.13.0
  yarn.lock
Labels: DSFR

#4895 Rendre les boutons de retour prise de RDV usager + accessible
  app/views/search/_creneau_selection.html.slim
  app/views/search/_motif_selection.html.slim
  app/views/search/_selected_motif_recap.html.slim
Labels: a11y

#4909 Usager: remove bootstrap jumbotron
  app/javascript/stylesheets/application.scss
Labels: DSFR

#4910 Usager: remove bootstrap nav and navbar
  app/javascript/stylesheets/application.scss
Labels: DSFR

#4886 Passage des erreurs de validation au DSFR
  app/views/application/_model_errors.html.slim
Labels: DSFR

#4906 Migration des boutons d’inscription atelier collectif au DSFR et a11y
  app/javascript/stylesheets/components/_utilities.scss
  app/views/search/_creneau_selection.html.slim
  app/views/search/_rdv_collectif.html.slim
Labels: a11y, DSFR

#4924 Fix: agent agenda off days contrast
  app/helpers/absences_helper.rb
  app/services/off_days.rb
  spec/controllers/admin/api/agenda/absences_controller_spec.rb
  spec/features/agents/rdvs_collectifs/agent_can_create_rdv_collectif_spec.rb
  spec/services/off_days_spec.rb
Labels: a11y

#4931 Use DSFR icons RDV summary wizard
  app/views/users/rdv_wizard_steps/_rdv_wizard_summary.html.slim
Labels: DSFR

#4925 Fix: suppression de l’icône en doublon mot de passe de l’agent est trop faible
  app/services/password_checker.rb
Labels: DSFR

#4928 Fix : icône lien externe en double edition masse motif
  app/views/admin/territories/motifs/batch_edit.html.slim
Labels: DSFR

#4927 Suppression de l’ancien layout flash
  app/views/layouts/_flash.html.slim
  spec/views/flash_spec.rb
Labels: DSFR

#4926 Migration invitation usager et reset password agent au DSFR
  app/javascript/application.js
  app/javascript/application_agent_config.js
  app/javascript/components/show-hide-password.js
  app/javascript/stylesheets/structure/_authentication.scss
  app/views/common/form/_new_password_input.html.slim
  app/views/devise/passwords/edit.html.slim
  app/views/devise/passwords/new.html.slim
  app/views/users/invitations/edit.html.slim
  config/locales/models/user.fr.yml
  spec/features/agents/account/agent_can_reset_his_password_spec.rb
  spec/features/users/account/user_signs_up_and_signs_in_spec.rb
Labels: DSFR

#4929 Utilisation des boutons DSFR pour la sélection de créneau
  app/javascript/stylesheets/components/_utilities_dsfr.scss
  app/views/search/_creneaux.html.slim
Labels: a11y, DSFR
