Repository betagouv/rdv-service-public, pull requests merged in 2025-02, with the labels that each got.

#5042 Ajout des liens d’évitements (skiplinks) côté usager
  Gemfile.lock
  app/views/layouts/application_base.html.slim
Labels: a11y, DSFR

#5056 Fournir `meeting_point_id` dans le job de synchro ANTS
  app/jobs/ants/sync_appointment_job.rb
  app/lib/ants_api.rb
  app/models/concerns/ants/appointment_serializer_and_listener.rb
  spec/jobs/ants/sync_appointment_job_spec.rb
  spec/models/concerns/ants/appointment_serializer_and_listener_spec.rb
  spec/support/ants_stubs.rb
Labels: ANTS

#4969 Migration user form au DSFR
  app/views/application/_model_errors.html.slim
  app/views/users/users/_form.html.slim
Labels: a11y, DSFR

#5067 ANTS: ne plus valider le statut des dossiers inutilement côté agent
  app/form_models/admin/user_form.rb
  app/form_models/beneficiaire_form.rb
  app/form_models/relative_user_form.rb
  app/form_models/user_rdv_wizard.rb
  app/models/user.rb
  app/validators/ants_pre_demande_number_format_validator.rb
  app/validators/ants_pre_demande_number_status_validation.rb
  app/validators/ants_pre_demande_number_validation.rb
  config/locales/models/user.fr.yml
  spec/features/agents/users/agent_can_create_user_for_rdv_mairie_spec.rb
  spec/features/users/online_booking/on_rdv_mairie_spec.rb
  spec/form_models/admin/user_form_spec.rb
  spec/form_models/beneficiaire_form_spec.rb
  spec/form_models/relative_user_form_spec.rb
  spec/form_models/user_rdv_wizard_spec.rb
Labels: ANTS

#5084 Correction du hover sur les boutons full calendar
  app/javascript/stylesheets/components/_calendar.scss
Labels: a11y

#5092 a11y: ajout du label manquant sur l’autocomplete d’adresse
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/application_agent_config.scss
  app/javascript/stylesheets/components/_search_form.scss
  app/views/search/address_selection/_search_form_section.html.slim
Labels: a11y
